= Лабораторная работа 1

== Жуламанова Арина Маратовна КЭ-413

<<< 

== Оглавление:
. Цель работы;
. Введение;
. Описание
.. Разработка кода/юнит тестирование;
.. Unit тестирование;
.. Тестирование ПО;
. Юнит тесты;
 

<<<

== Цель работы
Ознакомиться с оформлением документов в Asciidoc.
Познакомиться с основными правилами кодирования в C++ и C#.

<<<

== Введение
Кодирование - это написание кода, по существующей архитектуре, спецификации методов, интерфейсов и т.д. 
Метран использует только объектно-ориентированные языки:

* С++ для встроенного ПО;
* С# для ПО высокого уровня;

Для того, чтобы все члены команды понимали друг друга, используется стандарт кодирования:

* Общий стиль написания кода (отступы, пробелы, переносы строк и т.д.)
* Правила и договоренности по приемам программирования (всегда инициализировать переменную, всегда проверять указатели, делать проверку значения с перемнной и т.д.)

<<<

== Описание

=== Разработка кода/юнит тестирование

- Использование шаблонов проектирования (хотя это больше относится к разработке архитектуры):

* Стандартные подходы к решению частных задач проблем при разработке ПО;
* Пример, обработка события от кнопки, происходит по шаблону Observer;
* Для создания объектов используется шаблон Factory;
* Для того, чтобы сделать приложение, которое может работать только в единственном экземпляре, используется шаблон Singleton;

- Статическая проверка кода;
- Lint
* Для проверки соответсвия С++ стандартам и общепринятым правилам кодирования;
- Code Analysis

* Для проверки соответсвия С++ стандартам и общепринятым правилам кодирования;

<<<

=== Unit тестирование:

* Тестирование и проверка, что методы и функции соответсвуют спецификации;
* Поиск потенциальных ошибок в коде;
* Защита от изменения другми разработчиками;

<<<

=== Тестирование ПО:

* Сбор информации о потребноснтях;
* Анализ;
* Создание кода;
* Тестирование; 
* Развертывание;

При обнаружении ошибки на стадии сбора информации о потребностях для кего исправления могут потребоваться определенные расходы. Однако, если эта ошибка будет обнаружена на стадии тестирования, то расходы на ее исправление будут значительно выше. при замене каскадной модели процесса на интеративную повышается вероятность обнаружения ошибки на ранних стадиях разработки, что позволяет снизить расходы на ее исправление.

В традиционной каскадной модели процесс тестирования начинается только после завершения всех этапов разработки. В интерактивной модели тестирование начинается на ранних стадиях разработки и продолжается на протяжении всего жизненного цикла ПО. Это позволяет выявлять ошибки на ранних стадиях, когда их исправление требует меньших затрат.

<<<

=== Юнит тесты;
* Функциональное тестирование;
* Нефункциональное тестирование;
* Регрессионное тестирование;
* Стресс тесты, нагрузочные тесты, тесты стабильности;
* Смок тесты.

<<<

== Заключение
Ознакомилась с оформлением документов в Asciidoc.
В ходе лабораторной работы были изучены основные аспекты разработки и тестирования программного обеспечения. Были рассмотрены методы юнит-тестирования, а также подходы к тестированию на различных этапах жизненного цикла ПО. Полученные знания помогут в дальнейшем при разработке качественного и надежного программного обеспечения.